language: go
go:
  - tip
before_install:
  - export GO15VENDOREXPERIMENT=1
  - go get github.com/mattn/gom
script:
  - $HOME/gopath/bin/gom install
  - $HOME/gopath/bin/gom test -v
  - $HOME/gopath/bin/gom test -v ./github
